Zombie Science Villager
ScicraftLearn/MineLabs pull request #393
Opened 2022-10-11 12:24 UTC by pixar02

2022-10-11 12:38 UTC, pixar02 commented
solves #288

2022-10-13 13:25 UTC, smtdm commented
Hands of the villager are white instead of green.
![afbeelding](https://user-images.githubusercontent.com/26555903/195608788-af82fc80-b48a-46a4-b6b5-0e6c14cd0568.png)

2022-10-13 13:30 UTC, smtdm requested changes
Change zombievillager hands from white to green

2022-10-13 19:59 UTC, smtdm approved these changes
Works

2022-10-13 19:59 UTC, merged