Balloon refactor
ScicraftLearn/MineLabs pull request #394
Opened 2022-10-11 16:42 UTC by BertJorissen

Try to add the balloon like we implemented for the Nerdland-workshop to add to main.

2022-10-11 19:51 UTC, pixar02 requested changes
![image](https://user-images.githubusercontent.com/7142721/195185075-d39b6a6d-531d-4412-b0e3-59f75a3ae9f3.png)

BALLOON_MODEL is used in client only. See error above, instant crash for server.
use `new Identifier(MineLabs.MODID, "balloon")` instead of `new Identifier("minelabs:balloon")`

2022-10-11 20:27 UTC, smtdm requested changes
Lots of small bugs. 
If a player has ever holded a baloon in the offhand the effect is applied, even if the balloon is removed.
Visual bugs when an entity moves or teleports while attached to a balloon.
Visual bugs when an entity with a hitbox larger than 2 blocks is attached to a balloon.
Balloons stay floating after the entity has despawend.
Horses with a balloon drop to the floor when a player rides it.

2023-01-26 15:41 UTC, smtdm approved these changes
Good enough for now

2023-01-26 15:48 UTC, pixar02 approved these changes

2023-01-26 15:48 UTC, merged