Cosmetic burner
ScicraftLearn/Minelabs pull request #601
Opened 2023-04-07 16:17 UTC by pixar02

Added a Bunsen burner
Right click to toggle blue flame (adds/removes oxygen)
Flint and steel to turn on
Water should turn of the flame
Same behavior as Microscope and tuberack (height changes on lab counters)

2023-04-08 10:42 UTC, JoeyDP approved these changes
Code looks good. Haven't tested in game.

2023-04-08 13:28 UTC, smtdm requested changes
Cannot turn off the bunsenburner? Right-clicking with a bucket of water just places the water against the bunsenburner.
Add fire charge to the list of items that can light the bunsenburner

2023-04-09 10:29 UTC, JoeyDP commented on src/main/java/be/uantwerpen/minelabs/block/LabBlock.java
> +        // TODO TRIGGER NEIGHBOR UPDATE
I think neighbour updates are triggered by MC, you don't have to manually call it.

2023-04-09 21:06 UTC, JoeyDP approved these changes

2023-04-11 08:07 UTC, JoeyDP approved these changes

2023-04-11 13:16 UTC, smtdm approved these changes
Works as intende

2023-04-11 13:18 UTC, merged