Subatom/fields
ScicraftLearn/Minelabs pull request #874
Opened 2024-04-09 12:11 UTC by JoeyDP

Closes #845, #846

2024-07-16 18:53 UTC, smtdm commented
#846 Fields at the border get immediately replaced by atomic floor upon breaking them. No items drop.

2024-07-16 18:59 UTC, smtdm requested changes, later dismissed
see comment ^

2024-07-17 14:42 UTC, JoeyDP commented
@smtdm do you mean the world border? Or the floor?

2026-01-21 20:56 UTC, smtdm approved these changes
Good job Joey

2026-01-21 20:56 UTC, merged